from typing import Any

from promptarmor.policies.engine import PolicyAction, PolicyRule


class MCPGuardPolicyGenerator:
    def __init__(self, namespace: str = "promptarmor"):
        self.namespace = namespace

    def generate(self, rules: list[PolicyRule]) -> dict[str, Any]:
        mcpguard_rules: list[dict[str, Any]] = []
        for rule in rules:
            mcpguard_rule = self._convert_rule(rule)
            if mcpguard_rule:
                mcpguard_rules.append(mcpguard_rule)

        return {
            "version": "1.0",
            "namespace": self.namespace,
            "metadata": {
                "generator": "promptarmor",
                "description": "Policy generated by PromptArmor for MCPGuard",
            },
            "rules": mcpguard_rules,
        }

    def _convert_rule(self, rule: PolicyRule) -> dict[str, Any] | None:
        action_map = {
            PolicyAction.ALLOW: "allow",
            PolicyAction.BLOCK: "deny",
            PolicyAction.FLAG: "log",
            PolicyAction.SANITIZE: "sanitize",
            PolicyAction.LOG: "log",
            PolicyAction.REDIRECT: "redirect",
        }

        mcpguard_action = action_map.get(rule.action)
        if mcpguard_action is None:
            return None

        mcpguard_rule: dict[str, Any] = {
            "id": f"{self.namespace}_{rule.id}",
            "name": rule.name,
            "action": mcpguard_action,
            "priority": rule.priority,
            "enabled": rule.enabled,
        }

        conditions = rule.conditions
        mcpguard_conditions: dict[str, Any] = {}
        if "score_min" in conditions:
            mcpguard_conditions["score_min"] = conditions["score_min"]
        if "source" in conditions:
            mcpguard_conditions["source"] = conditions["source"]
        if "category" in conditions:
            mcpguard_conditions["category"] = conditions["category"]
        if mcpguard_conditions:
            mcpguard_rule["conditions"] = mcpguard_conditions

        if rule.description:
            mcpguard_rule["description"] = rule.description

        return mcpguard_rule

    def generate_yaml(self, rules: list[PolicyRule]) -> str:
        import yaml

        data = self.generate(rules)
        return yaml.dump(data, default_flow_style=False, sort_keys=False)
